version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade pip
  pre_build:
    commands:
      - cd python-common
  build:
    commands:
      - chmod +x build.sh
      - ./build.sh
  post_build:
    commands:
      - aws lambda publish-layer-version --layer-name python-common --zip-file fileb://layer.zip --compatible-runtimes python3.12
artifacts:
  files:
    - python-common/layer.zip
